=== vinay-th/revision-workspace/XML/Assignment-1/demo.dtd
<!ELEMENT Letter (Contact, Salutation, Paragraph, Closing, Signature)>
<!ELEMENT Contact (Name, Address, City, Pin, Flag)>
<!ATTLIST Contact type CDATA #FIXED "Sender">
<!ELEMENT Name (#PCDATA)>
<!ELEMENT Address (#PCDATA)>
<!ELEMENT City (#PCDATA)>
<!ELEMENT Pin (#PCDATA)>
<!ELEMENT Flag EMPTY>
<!ATTLIST Flag Gender (Male | Female) "Male">
<!ELEMENT Salutation (#PCDATA)>
<!ELEMENT Paragraph (#PCDATA)>
<!ELEMENT Closing (#PCDATA)>
<!ELEMENT Signature (#PCDATA)>

=== vinay-th/revision-workspace/XML/Assignment-1/demo.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE Letter SYSTEM "dtd/demo.dtd">
<Letter>
    <Contact type="Sender">
        <Name>Vansh</Name>
        <Address>XYZ</Address>
        <City>Ahmedabad</City>
        <Pin>777777</Pin>
        <Flag Gender="Male"></Flag>
    </Contact>
    <Salutation>
        Hello bro
    </Salutation>
    <Paragraph>
        This is a letter to you
    </Paragraph>
    <Closing>
        Thanks
    </Closing>
    <Signature>
        Vansh
    </Signature>
</Letter>
