=== vinay-th/revision-workspace/XML/Assignment-2/dtd/1.dtd
<!ELEMENT Student (PersonalInfo)>
<!ELEMENT PersonalInfo (RollNo, Name, Address, Mobile, DOB, Age, Qualification)>
<!ELEMENT RollNo (#PCDATA)>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT Address (#PCDATA)>
<!ELEMENT Mobile (#PCDATA)>
<!ELEMENT DOB (#PCDATA)>
<!ELEMENT Age (#PCDATA)>
<!ELEMENT Qualification (#PCDATA)>

=== vinay-th/revision-workspace/XML/Assignment-2/q1.xml
<?xml version="1.0"?>
<!DOCTYPE Student SYSTEM "dtd/1.dtd">
<Student>
	<PersonalInfo>
		<RollNo>1</RollNo>
		<Name>eszg</Name>
		<Address>gzrfg</Address>
		<Mobile>15451981265</Mobile>
		<DOB>22-12-2022</DOB>
		<Age>35</Age>
		<Qualification>fzdsfg</Qualification>
	</PersonalInfo>
</Student>
