=== vinay-th/revision-workspace/XML/Assignment-2/dtd/4.dtd
<!ELEMENT Student (Name, PersonalInfo, Result)>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT PersonalInfo (Address, Birthdate, Gender, MobileNo, Mail)>
<!ELEMENT Address (#PCDATA)>
<!ELEMENT Birthdate (#PCDATA)>
<!ELEMENT Gender (Male | Female)>
<!ELEMENT Male (#PCDATA)>
<!ELEMENT Female (#PCDATA)>
<!ELEMENT MobileNo (#PCDATA)>
<!ELEMENT Mail (#PCDATA)>
<!ELEMENT Result (Total, Percentage, Grade)>
<!ELEMENT Total (#PCDATA)>
<!ELEMENT Percentage (#PCDATA)>
<!ELEMENT Grade (Pass | First | Dist | Second | Fail)>
<!ELEMENT Pass (#PCDATA)>
<!ELEMENT First (#PCDATA)>
<!ELEMENT Dist (#PCDATA)>
<!ELEMENT Second (#PCDATA)>
<!ELEMENT Fail (#PCDATA)>

=== vinay-th/revision-workspace/XML/Assignment-2/q4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Student SYSTEM "dtd/4.dtd">
<Student>
    <Name>Ravi Kumar</Name>
    <PersonalInfo>
        <Address>123, MG Road, Mumbai</Address>
        <Birthdate>2001-05-20</Birthdate>
        <Gender><Male/></Gender>
        <MobileNo>9876543210</MobileNo>
        <Mail>ghghcctcc@vv.com</Mail>
    </PersonalInfo>
    <Result>
        <Total>450</Total>
        <Percentage>90</Percentage>
        <Grade><First/></Grade>
    </Result>
</Student>
